
const groups={A:["Meksiko","Afrika Selatan","Korea Selatan","Ceko"],B:["Kanada","Bosnia dan Herzegovina","Qatar","Swiss"],C:["Brasil","Maroko","Haiti","Skotlandia"],D:["Amerika Serikat","Paraguay","Australia","Turki"],E:["Jerman","Curaçao","Pantai Gading","Ekuador"],F:["Belanda","Jepang","Swedia","Tunisia"],G:["Belgia","Mesir","Iran","Selandia Baru"],H:["Spanyol","Cape Verde","Arab Saudi","Uruguay"],I:["Prancis","Senegal","Irak","Norwegia"],J:["Argentina","Aljazair","Austria","Yordania"],K:["Portugal","RD Kongo","Uzbekistan","Kolombia"],L:["Inggris","Kroasia","Ghana","Panama"]};
const names={home:"Dashboard",groups:"Negara & Grup",matches:"Jadwal & Skor",bracket:"Bagan Gugur",party:"Jadwal Nobar",data:"Data"};
function esc(s){return String(s).replaceAll("'","\\'")}
function mkState(){let s={teams:{},matches:[],bracket:{},party:[]};Object.entries(groups).forEach(([g,ts])=>ts.forEach(t=>s.teams[t]={g,status:"active",fav:false}));s.matches=mkMatches();mkSlots().forEach(x=>s.bracket[x.id]={a:x.a,b:x.b,w:""});return s}
function mkMatches(){let pairs=[[0,1],[2,3],[0,2],[1,3],[0,3],[1,2]],start=new Date("2026-06-11T20:00:00"),n=0,arr=[];Object.entries(groups).forEach(([g,ts])=>pairs.forEach((p,i)=>{let d=new Date(start.getTime()+n*6*3600000);arr.push({id:g+"-"+(i+1),g,stage:"Fase Grup",date:d.toISOString().slice(0,16),h:ts[p[0]],a:ts[p[1]],hs:"",as:""});n++}));return arr}
function mkSlots(){let a=[];for(let i=1;i<=16;i++)a.push({id:"R32-"+i,a:"Tim R32 "+i+"A",b:"Tim R32 "+i+"B"});for(let i=1;i<=8;i++)a.push({id:"R16-"+i,a:"Pemenang R32-"+(i*2-1),b:"Pemenang R32-"+i*2});for(let i=1;i<=4;i++)a.push({id:"QF-"+i,a:"Pemenang R16-"+(i*2-1),b:"Pemenang R16-"+i*2});for(let i=1;i<=2;i++)a.push({id:"SF-"+i,a:"Pemenang QF-"+(i*2-1),b:"Pemenang QF-"+i*2});a.push({id:"FINAL",a:"Pemenang SF-1",b:"Pemenang SF-2"});return a}
let state=(()=>{try{return JSON.parse(localStorage.wc_nobar_2026)||mkState()}catch{return mkState()}})();
function save(){localStorage.wc_nobar_2026=JSON.stringify(state);render()}
function go(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("show"));document.getElementById(id).classList.add("show");document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("on",b.dataset.page==id));title.textContent=names[id]}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page));
function fmt(d){return d?new Date(d).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}):"-"}
function statusText(x){return x=="qualified"?"✅ Lolos":x=="eliminated"?"❌ Gugur":"🟢 Aktif"}
function setStatus(t,x){state.teams[t].status=x;save()} window.setStatus=setStatus;
function fav(t){state.teams[t].fav=!state.teams[t].fav;save()} window.fav=fav;
function renderHome(){let ts=Object.keys(state.teams);sTeams.textContent=ts.length;sQ.textContent=ts.filter(t=>state.teams[t].status=="qualified").length;sE.textContent=ts.filter(t=>state.teams[t].status=="eliminated").length;sN.textContent=state.party.length;let fs=ts.filter(t=>state.teams[t].fav);favBox.innerHTML=fs.length?fs.map(t=>`<span class="chip">⭐ ${t}</span>`).join(""):"Belum ada tim favorit. Klik ⭐ pada halaman Negara & Grup."}
function row(t){let st=state.teams[t],c=st.status=="qualified"?"q":st.status=="eliminated"?"e":"";return `<div class="team ${c} ${st.fav?"f":""}"><div><div class="tname">${t}</div><small>${statusText(st.status)}</small></div><div class="acts"><button class="mini star" onclick="fav('${esc(t)}')">${st.fav?"★":"☆"}</button><button class="mini ok" onclick="setStatus('${esc(t)}','qualified')">Lolos</button><button class="mini no" onclick="setStatus('${esc(t)}','eliminated')">Gugur</button><button class="mini neutral" onclick="setStatus('${esc(t)}','active')">Aktif</button></div></div>`}
function renderGroups(){let q=search.value.toLowerCase(),f=filter.value;groupGrid.innerHTML="";Object.entries(groups).forEach(([g,ts])=>{let list=ts.filter(t=>t.toLowerCase().includes(q)&&(f=="all"||state.teams[t].status==f||(f=="favorite"&&state.teams[t].fav)));if(!list.length)return;let div=document.createElement("div");div.className="group";div.innerHTML=`<div class="gtitle"><span>Grup ${g}</span><span>${list.length} negara</span></div>`+list.map(row).join("");groupGrid.appendChild(div)})}
function renderFilters(){if(gFilter.children.length>1)return;Object.keys(groups).forEach(g=>{let o=document.createElement("option");o.value=g;o.textContent="Grup "+g;gFilter.appendChild(o)})}
function renderMatches(){let gf=gFilter.value,mf=mFilter.value;matchList.innerHTML=state.matches.filter(m=>(gf=="all"||m.g==gf)&&(mf=="all"||(mf=="done"&&m.hs!==""&&m.as!=="")||(mf=="pending"&&(m.hs===""||m.as==="")))).map(m=>`<div class="match"><div class="meta"><span>Grup ${m.g} • ${m.stage}</span><span>${fmt(m.date)}</span></div><div class="teams"><div class="sidebox"><h3>${m.h}</h3><div class="acts"><button class="mini ok" onclick="setStatus('${esc(m.h)}','qualified')">Lolos</button><button class="mini no" onclick="setStatus('${esc(m.h)}','eliminated')">Gugur</button><button class="mini star" onclick="fav('${esc(m.h)}')">Favorit</button></div></div><div class="score"><input type="number" min="0" value="${m.hs}" onchange="score('${m.id}','hs',this.value)">VS<input type="number" min="0" value="${m.as}" onchange="score('${m.id}','as',this.value)"></div><div class="sidebox"><h3>${m.a}</h3><div class="acts"><button class="mini ok" onclick="setStatus('${esc(m.a)}','qualified')">Lolos</button><button class="mini no" onclick="setStatus('${esc(m.a)}','eliminated')">Gugur</button><button class="mini star" onclick="fav('${esc(m.a)}')">Favorit</button></div></div></div></div>`).join("")}
function score(id,k,v){let m=state.matches.find(x=>x.id==id);m[k]=v;save()} window.score=score;
function renderBracket(){let cols=[["32 Besar","R32",16],["16 Besar","R16",8],["Perempat Final","QF",4],["Semifinal","SF",2],["Final","FINAL",1]];bracketBox.innerHTML=cols.map(c=>{let cards="";if(c[1]=="FINAL")cards=bcard("FINAL");else for(let i=1;i<=c[2];i++)cards+=bcard(c[1]+"-"+i);return `<div class="bcol"><h3>${c[0]}</h3>${cards}</div>`}).join("")}
function bcard(id){let b=state.bracket[id]||{a:"",b:"",w:""};return `<div class="bmatch"><small>${id}</small><input value="${b.a}" onchange="bedit('${id}','a',this.value)" placeholder="Tim 1"><input value="${b.b}" onchange="bedit('${id}','b',this.value)" placeholder="Tim 2"><input value="${b.w}" onchange="bedit('${id}','w',this.value)" placeholder="Pemenang"><button onclick="bw('${id}')">Lolos</button></div>`}
function bedit(id,k,v){state.bracket[id]||(state.bracket[id]={a:"",b:"",w:""});state.bracket[id][k]=v;localStorage.wc_nobar_2026=JSON.stringify(state)} window.bedit=bedit;
function bw(id){let w=(state.bracket[id]?.w||"").trim();if(state.teams[w]){state.teams[w].status="qualified";save();alert(w+" ditandai lolos.")}else alert("Isi nama pemenang sesuai nama negara di daftar grup.")} window.bw=bw;
partyForm.onsubmit=e=>{e.preventDefault();state.party.push({t:pTitle.value,d:pDate.value,p:pPlace.value,n:pNote.value});partyForm.reset();save()}
function renderParty(){partyList.innerHTML=state.party.length?state.party.map((p,i)=>`<div class="party"><h3>${p.t}</h3><p>🕒 ${fmt(p.d)}</p><p>📍 ${p.p||"-"}</p><p>📝 ${p.n||"-"}</p><button class="light" onclick="delParty(${i})">Hapus</button></div>`).join(""):"Belum ada agenda nobar."}
function delParty(i){state.party.splice(i,1);save()} window.delParty=delParty;
function backup(){let blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="backup_nobar_wc2026.json";a.click()} window.backup=backup;
importFile.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();alert("Import berhasil")}catch{alert("File tidak valid")}};r.readAsText(f)}
function resetAll(){if(confirm("Reset semua data?")){state=mkState();save()}} window.resetAll=resetAll;
[search,filter,gFilter,mFilter].forEach(el=>el.oninput=render);
function render(){renderHome();renderFilters();renderGroups();renderMatches();renderBracket();renderParty()}
render();
